require("plugins.colorizer")
require("plugins.statusline")
require("plugins.barbar")
require("plugins.gitsigns")
require("plugins.indent-blankline")
-- require("plugins.chadtree")
require("plugins.tree")
require("plugins.trouble")

require("plugins.lsp")
require("plugins.treesitter")

require("plugins.easymotion")
require("plugins.kommentary")
require("plugins.todo")
require("plugins.completion")
require("plugins.formatter")

require("plugins.tmux")
require("plugins.telescope")
